### PR TITLE
feat: support azure mistral large (#80)

### PR DESCRIPTION
**Pull request by vladisavvv**

### CODE REVIEW

**Comment by vladisavvv** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-openai-pr-87.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by vladisavvv** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-openai-pr-87.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by vladisavvv** [comment]
/deploy-review


>Environment URL: https://chat-ai-dial-adapter-openai-pr-87.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by Oleksii-Klimov — APPROVED** [review]

**Comment by vladisavvv** [comment]
/deploy-review

>Environment URL: https://chat-ai-dial-adapter-openai-pr-87.nightly-test.deltixhub.io
>E2E tests status: failed

**Pull request merged**
