### PR TITLE
fix: propagating per request key

### PR DESCRIPTION
**Pull request by adubovik**
As per [spec](https://github.com/epam/ai-dial-core/issues/124)

### CODE REVIEW

**Comment by adubovik** [comment]
/deploy-review
>Deployment status: success

**Comment by adubovik** [comment]
/deploy-review
>Deployment status: success

**Comment by adubovik** [comment]
/deploy-review
>Deployment status: success

**Comment by adubovik** [comment]
/deploy-review
>Deployment status: success

**Review by Oleksii-Klimov — APPROVED** [review]

**Review by Oleksii-Klimov — APPROVED** [review]

**Pull request merged**
