### PR TITLE
feat: supported Databricks chat completions and embeddings models (#96)

### LINKED ISSUE #96: Support Databricks models
Support Databricks models as per [documentation](https://learn.microsoft.com/en-us/azure/databricks/machine-learning/foundation-models/):
1. chat completion models: `databricks-dbrx-instruct`, `databricks-mixtral-8x7b-instruct`, `databricks-llama-2-70b-chat`
2. embedding model: `databricks-bge-large-en`

The text completion models _(`databricks-mpt-7b-instruct`, `databricks-mpt-30b-instruct`)_ are out of scope.

### PR DESCRIPTION
**Pull request by adubovik**
Resolves https://github.com/epam/ai-dial-adapter-openai/issues/96

### CODE REVIEW

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-openai-pr-95.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by adubovik** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/465643)

**Comment by adubovik** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/465658)

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-openai-pr-95.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by vladisavvv — DISMISSED** [review]

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-openai-pr-95.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-openai-pr-95.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-openai-pr-95.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by vladisavvv — APPROVED** [review]

**Review by vladisavvv — APPROVED** [review]

**Pull request merged**
